openapi: 3.0.3
info:
  title: M03 Notification Service API
  version: 1.0.0
  description: |
    OpenAPI contract for M03 Notification Service public REST routes.
    Source alignment:
    - Canonical spec: viralForge/specs/M03-Notification-Service.md
servers:
  - url: /
security:
  - bearerAuth: []
tags:
  - name: Notifications
paths:
  /v1/notifications:
    get:
      tags: [Notifications]
      summary: List notifications
      operationId: listNotifications
      parameters:
        - $ref: '#/components/parameters/StatusQuery'
        - $ref: '#/components/parameters/TypeQuery'
        - $ref: '#/components/parameters/LimitQuery'
        - $ref: '#/components/parameters/CursorQuery'
      responses:
        '200':
          description: Notification list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationListResponse'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalError' }
  /v1/notifications/unread-count:
    get:
      tags: [Notifications]
      summary: Get unread notification count
      operationId: getUnreadCount
      responses:
        '200':
          description: Unread count
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnreadCountResponse'
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalError' }
  /v1/notifications/{id}/read:
    post:
      tags: [Notifications]
      summary: Mark notification as read
      operationId: markNotificationRead
      parameters:
        - $ref: '#/components/parameters/NotificationID'
        - $ref: '#/components/parameters/XRequestID'
      responses:
        '200':
          description: Read status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadNotificationResponse'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '404': { $ref: '#/components/responses/NotFound' }
        '500': { $ref: '#/components/responses/InternalError' }
  /v1/notifications/{id}/archive:
    post:
      tags: [Notifications]
      summary: Archive notification
      operationId: archiveNotification
      parameters:
        - $ref: '#/components/parameters/NotificationID'
        - $ref: '#/components/parameters/XRequestID'
      responses:
        '200':
          description: Archive status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArchiveNotificationResponse'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '404': { $ref: '#/components/responses/NotFound' }
        '500': { $ref: '#/components/responses/InternalError' }
  /v1/notifications/bulk-action:
    post:
      tags: [Notifications]
      summary: Perform bulk action on notifications
      operationId: bulkNotificationAction
      parameters:
        - $ref: '#/components/parameters/IdempotencyKey'
        - $ref: '#/components/parameters/XRequestID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkActionRequest'
      responses:
        '200':
          description: Bulk action result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkActionResponse'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '413': { $ref: '#/components/responses/PayloadTooLarge' }
        '500': { $ref: '#/components/responses/InternalError' }
  /v1/notifications/preferences:
    get:
      tags: [Notifications]
      summary: Get notification preferences
      operationId: getNotificationPreferences
      responses:
        '200':
          description: Preferences
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPreferencesResponse'
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalError' }
    put:
      tags: [Notifications]
      summary: Update notification preferences
      operationId: updateNotificationPreferences
      parameters:
        - $ref: '#/components/parameters/XRequestID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePreferencesRequest'
      responses:
        '200':
          description: Preferences updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdatePreferencesResponse'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalError' }
  /v1/notifications/scheduled/{id}:
    delete:
      tags: [Notifications]
      summary: Cancel scheduled notification (admin)
      operationId: cancelScheduledNotification
      parameters:
        - $ref: '#/components/parameters/ScheduleID'
        - $ref: '#/components/parameters/XRequestID'
      responses:
        '200':
          description: Schedule cancelled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelScheduledResponse'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '404': { $ref: '#/components/responses/NotFound' }
        '409': { $ref: '#/components/responses/Conflict' }
        '500': { $ref: '#/components/responses/InternalError' }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    NotificationID:
      name: id
      in: path
      required: true
      schema: { type: string }
    ScheduleID:
      name: id
      in: path
      required: true
      schema: { type: string }
    XRequestID:
      name: X-Request-Id
      in: header
      required: true
      schema: { type: string }
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      required: true
      description: 7-day idempotency key for bulk mutations.
      schema: { type: string }
    StatusQuery:
      name: status
      in: query
      schema:
        type: string
        enum: [unread, read, archived]
    TypeQuery:
      name: type
      in: query
      schema:
        type: string
    LimitQuery:
      name: limit
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
    CursorQuery:
      name: cursor
      in: query
      schema:
        type: string
  schemas:
    NotificationItem:
      type: object
      properties:
        notification_id: { type: string }
        type: { type: string }
        title: { type: string }
        body: { type: string }
        action_url: { type: string }
        read_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
    PaginationData:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/NotificationItem'
        next_cursor:
          type: string
          nullable: true
        unread_count:
          type: integer
    NotificationListResponse:
      type: object
      properties:
        status: { type: string, example: success }
        data:
          $ref: '#/components/schemas/PaginationData'
    UnreadCountResponse:
      type: object
      properties:
        status: { type: string, example: success }
        data:
          type: object
          properties:
            unread_count: { type: integer }
    ReadNotificationResponse:
      type: object
      properties:
        status: { type: string, example: success }
        data:
          type: object
          properties:
            notification_id: { type: string }
            read_at:
              type: string
              format: date-time
    ArchiveNotificationResponse:
      type: object
      properties:
        status: { type: string, example: success }
        data:
          type: object
          properties:
            notification_id: { type: string }
            archived_at:
              type: string
              format: date-time
    BulkActionRequest:
      type: object
      required: [action, notification_ids]
      properties:
        action:
          type: string
          enum: [mark_read, mark_unread, archive, delete]
        notification_ids:
          type: array
          minItems: 1
          maxItems: 100
          items:
            type: string
    BulkActionResponse:
      type: object
      properties:
        status: { type: string, example: success }
        data:
          type: object
          properties:
            processed: { type: integer }
            failed: { type: integer }
    QuietHours:
      type: object
      properties:
        enabled: { type: boolean }
        start: { type: string, example: "22:00" }
        end: { type: string, example: "08:00" }
        timezone: { type: string, example: "America/New_York" }
    NotificationPreferences:
      type: object
      properties:
        email_enabled: { type: boolean }
        push_enabled: { type: boolean }
        sms_enabled: { type: boolean }
        in_app_enabled: { type: boolean }
        muted_types:
          type: array
          items: { type: string }
        quiet_hours:
          $ref: '#/components/schemas/QuietHours'
        language: { type: string }
        batching_enabled: { type: boolean }
    UpdatePreferencesRequest:
      allOf:
        - $ref: '#/components/schemas/NotificationPreferences'
    GetPreferencesResponse:
      type: object
      properties:
        status: { type: string, example: success }
        data:
          $ref: '#/components/schemas/NotificationPreferences'
    UpdatePreferencesResponse:
      type: object
      properties:
        status: { type: string, example: success }
        data:
          type: object
          properties:
            updated_at:
              type: string
              format: date-time
    CancelScheduledResponse:
      type: object
      properties:
        status: { type: string, example: success }
        data:
          type: object
          properties:
            schedule_id: { type: string }
            cancelled_at:
              type: string
              format: date-time
    ErrorResponse:
      type: object
      properties:
        status: { type: string, example: error }
        error:
          type: object
          properties:
            code: { type: string }
            message: { type: string }
            request_id: { type: string }
            details: {}
  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Missing or invalid auth
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: Insufficient access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Conflict:
      description: State conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    PayloadTooLarge:
      description: Too many notification IDs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
