openapi: 3.0.3
info:
  title: M18 Cache & State Management
  version: 1.0.0
  description: Internal cache API for mesh services. Mutating routes require Idempotency-Key with 7-day TTL; mismatched payload returns 409.
servers:
  - url: https://cache.internal
security:
  - bearerAuth: []
paths:
  /health:
    get:
      summary: Health check
      tags: [health]
      responses:
        '200':
          description: Service healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthReport'
        '503':
          description: Degraded / unhealthy
  /v1/cache/{key}:
    get:
      summary: Get cache value
      tags: [cache]
      security:
        - bearerAuth: []
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cache response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCacheResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Set cache value
      tags: [cache]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/CacheKey'
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutCacheRequest'
      responses:
        '201':
          description: Stored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutCacheResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
    delete:
      summary: Delete cache key
      tags: [cache]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/CacheKey'
        - $ref: '#/components/parameters/IdempotencyKey'
      responses:
        '200':
          description: Delete result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteCacheResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
  /v1/cache/invalidate:
    post:
      summary: Invalidate cache keys
      tags: [cache]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvalidateCacheRequest'
      responses:
        '200':
          description: Invalidation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidateCacheResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          $ref: '#/components/responses/Conflict'
  /v1/cache/metrics:
    get:
      summary: Cache metrics (JSON)
      tags: [metrics]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Metrics snapshot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    CacheKey:
      name: key
      in: path
      required: true
      schema:
        type: string
        maxLength: 512
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      required: true
      schema:
        type: string
      description: Required for mutating routes. Stored for 7 days with request hash; mismatch returns 409.
  responses:
    BadRequest:
      description: Invalid input
    Unauthorized:
      description: Missing/invalid bearer token
    Conflict:
      description: Idempotency conflict
    NotFound:
      description: Cache entry not found
  schemas:
    SuccessResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          type: object
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
        error:
          $ref: '#/components/schemas/ErrorPayload'
    ErrorPayload:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        request_id:
          type: string
    GetCacheResponse:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
          description: base64-encoded
        ttl_seconds:
          type: integer
        found:
          type: boolean
    PutCacheRequest:
      type: object
      required: [value]
      properties:
        value:
          type: string
          description: base64-encoded
        ttl_seconds:
          type: integer
          minimum: 1
    PutCacheResponse:
      type: object
      properties:
        key:
          type: string
        stored_at:
          type: string
          format: date-time
        ttl_seconds:
          type: integer
    DeleteCacheResponse:
      type: object
      properties:
        key:
          type: string
        deleted:
          type: boolean
    InvalidateCacheRequest:
      type: object
      required: [keys]
      properties:
        keys:
          type: array
          minItems: 1
          items:
            type: string
            maxLength: 512
    InvalidateCacheResponse:
      type: object
      properties:
        invalidated_count:
          type: integer
    MetricsResponse:
      type: object
      properties:
        hits:
          type: integer
        misses:
          type: integer
        evictions:
          type: integer
        memory_used_bytes:
          type: integer
    HealthReport:
      type: object
      properties:
        status:
          type: string
        timestamp:
          type: string
          format: date-time
        uptime_seconds:
          type: integer
        version:
          type: string
        checks:
          type: object
          additionalProperties:
            type: object
            properties:
              name:
                type: string
              status:
                type: string
              latency_ms:
                type: integer
              last_checked:
                type: string
                format: date-time
