openapi: 3.0.3
info:
  title: M39 Finance Service
  version: 1.0.0
  description: >
    Payments, refunds, balances, and provider webhooks. Mutating routes require
    Idempotency-Key stored with request hash for 7 days; mismatched payloads return 409.
servers:
  - url: /v1
security:
  - bearerAuth: []
paths:
  /healthz:
    get:
      summary: Liveness check
      security: []
      tags: [health]
      responses:
        '200': { description: Service alive }
  /readyz:
    get:
      summary: Readiness check
      security: []
      tags: [health]
      responses:
        '200': { description: Service ready }

  /transactions:
    post:
      summary: Create transaction
      tags: [transactions]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionRequest'
      responses:
        '201':
          description: Transaction created
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data: { $ref: '#/components/schemas/Transaction' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '409': { $ref: '#/components/responses/Conflict' }
    get:
      summary: List transactions
      tags: [transactions]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: user_id
          schema: { type: string }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 500, default: 20 }
        - in: query
          name: offset
          schema: { type: integer, minimum: 0, default: 0 }
      responses:
        '200':
          description: Transaction list
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          items:
                            type: array
                            items: { $ref: '#/components/schemas/Transaction' }
                          pagination: { $ref: '#/components/schemas/Pagination' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }

  /transactions/{id}:
    get:
      summary: Get transaction by id
      tags: [transactions]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Transaction
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data: { $ref: '#/components/schemas/Transaction' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '404': { $ref: '#/components/responses/NotFound' }

  /balances/{userID}:
    get:
      summary: Get user balance
      tags: [balances]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userID
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Balance
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data: { $ref: '#/components/schemas/Balance' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }

  /refunds:
    post:
      summary: Create refund
      tags: [refunds]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRefundRequest'
      responses:
        '201':
          description: Refund created
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data: { $ref: '#/components/schemas/Refund' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '409': { $ref: '#/components/responses/Conflict' }

  /webhooks/provider:
    post:
      summary: Provider webhook callback
      tags: [webhooks]
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ProviderWebhook' }
      responses:
        '202':
          description: Webhook accepted
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - type: object
                    properties:
                      data: { $ref: '#/components/schemas/WebhookAccepted' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '409': { $ref: '#/components/responses/Conflict' }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      required: true
      schema: { type: string }
      description: Required for mutating endpoints. Stored for 7 days with request hash; mismatched payload returns 409.
  responses:
    Unauthorized:
      description: Missing/invalid bearer token
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
    Forbidden:
      description: Caller not permitted
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
    BadRequest:
      description: Invalid input
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
    Conflict:
      description: Idempotency or state conflict
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }
  schemas:
    SuccessResponse:
      type: object
      properties:
        status: { type: string, example: success }
        message: { type: string }
        data: { type: object }
    ErrorResponse:
      type: object
      required: [status, code, message]
      properties:
        status: { type: string, example: error }
        code: { type: string }
        message: { type: string }
    Pagination:
      type: object
      properties:
        limit: { type: integer }
        offset: { type: integer }
        total: { type: integer }
    Transaction:
      type: object
      properties:
        transaction_id: { type: string }
        user_id: { type: string }
        campaign_id: { type: string }
        product_id: { type: string }
        provider: { type: string }
        provider_transaction_id: { type: string }
        amount: { type: number }
        currency: { type: string }
        platform_fee_rate: { type: number }
        status: { type: string }
        failure_reason: { type: string }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
        succeeded_at: { type: string, format: date-time }
        failed_at: { type: string, format: date-time }
        refunded_at: { type: string, format: date-time }
    CreateTransactionRequest:
      type: object
      required: [user_id, amount, provider]
      properties:
        user_id: { type: string }
        campaign_id: { type: string }
        product_id: { type: string }
        provider: { type: string, enum: [stripe, paypal, moonpay] }
        provider_transaction_id: { type: string }
        amount: { type: number }
        currency: { type: string, default: USD }
        traffic_source: { type: string }
        user_tier: { type: string }
    Refund:
      type: object
      properties:
        refund_id: { type: string }
        transaction_id: { type: string }
        user_id: { type: string }
        amount: { type: number }
        currency: { type: string }
        reason: { type: string }
        created_at: { type: string, format: date-time }
    CreateRefundRequest:
      type: object
      required: [transaction_id, user_id, amount]
      properties:
        transaction_id: { type: string }
        user_id: { type: string }
        amount: { type: number }
        reason: { type: string }
    Balance:
      type: object
      properties:
        user_id: { type: string }
        pending_balance: { type: number }
        negative_balance: { type: number }
        currency: { type: string }
        last_transaction_id: { type: string }
        updated_at: { type: string, format: date-time }
    ProviderWebhook:
      type: object
      properties:
        webhook_id: { type: string }
        provider: { type: string }
        event_type: { type: string }
        provider_event_id: { type: string }
        provider_transaction_id: { type: string }
        transaction_id: { type: string }
        user_id: { type: string }
        amount: { type: number }
        currency: { type: string }
        reason: { type: string }
    WebhookAccepted:
      type: object
      properties:
        webhook_id: { type: string }
        status: { type: string }
        processed: { type: string, format: date-time }
